steps:
- name: gcr.io/cloud-builders/gcloud 
  entrypoint: "bash"
  args:
  - "-c"
  - |
  RESPONSE=$(curl -i 10.100.136.3:443 | grep HTTP | cut -d' ' -f2) if [ "200" != "$$RESPONSE" ]; then exit 1; fi:
