apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demoliverpool
  name: app-totalplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoliverpool
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoliverpool
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/lvp-lab-cicd-central/artifacts-cicd-test/democicd-cont
        name: app-totalplay
        resources: {}
status: {}
