apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: cv-gcp-
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/lvp-lab-cicd-artifact-images/artifacts-cicd-test/democicd-cont:latest
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests: 
    - deployment.yaml
