apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: cv-gcp-
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/demototalplay/arti-demo-totalplay/totalplay-cont
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests: 
    - deployment.yaml