apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: pipeline-totalplay
  labels:
description: delivery pipeline
serialPipeline:
  stages:
  - targetId: dev  
  - targetId: qa
  - targetId: prod