apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: preview
  annotations: {}
  labels: {}
description: Target for preview environment
gke:
  cluster: projects/demototalplay/locations/us-central1-a/clusters/qa